// File generated by "melos run svg". Do not edit by hand.
// Copyright (c) 2023. The Hridayangam Authors. All rights reserved.

final class Asset {
  static const AssetIcons icons = AssetIcons();
  static const AssetNav nav = AssetNav();
}

final class AssetIcons {
  const AssetIcons();

  String get chat => 'assets/icons-bin/chat.svg.vec';
}
final class AssetNav {
  const AssetNav();

  String get search => 'assets/nav-bin/search.svg.vec';
  String get home => 'assets/nav-bin/home.svg.vec';
  String get add => 'assets/nav-bin/add.svg.vec';
  String get profile => 'assets/nav-bin/profile.svg.vec';
}
